//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int Id { get; set; }
        public Nullable<int> C_ { get; set; }
        public Nullable<System.DateTime> Время { get; set; }
        public string Понедельник { get; set; }
        public string Вторник { get; set; }
        public string Среда { get; set; }
        public string Четверг { get; set; }
        public string Пятница { get; set; }
        public string Суббота { get; set; }
    }
}
