//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public string Категория { get; set; }
        public int Группа { get; set; }
        public string Сроки_обучения { get; set; }
        public string Преподаватель { get; set; }
        public int Id { get; set; }
    }
}
