//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseDSEntities : DbContext
    {
        public DataBaseDSEntities()
            : base("name=DataBaseDSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lessons> lessons { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Graduates> Graduates { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Timetable> Timetable { get; set; }
    }
}
