//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int Id { get; set; }
        public string Категория { get; set; }
        public int Группа { get; set; }
        public string ФИО { get; set; }
        public string Дата_рождения { get; set; }
        public string Телефон { get; set; }
        public string Место_жительства { get; set; }
        public string Паспортные_данные { get; set; }
        public string Сумма_оплаты { get; set; }
        public string Сумма_задолженности { get; set; }
        public string Серия_и_номер_справки { get; set; }
        public string Дата_выдачи { get; set; }
        public string Кем_выдана { get; set; }
        public string Дата_выпуска { get; set; }
    }
}
